### ISSUE TITLE
Undersized buffer write during HexEncode leads to out of bounds panic

### ISSUE THREAD

**Issue by yunginnanet** [l0nax/go-spew#1]
### Symptom

```
(*ssh.channel)(0xc0004220c0)({
 chanType: (string) (len=12) "direct-tcpip",
 extraData: ([]uint8) (len=33 cap=33) {
panic: runtime error: index out of range [1] with length 1

goroutine 23 [running]:
github.com/l0nax/go-spew/spew.HexEncode({0xc000404464?, 0xc0004081e0?, 0xc00040215d?}, {0xc000404460?, 0x0?, 0x0?}, 0xa0?)
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/hex.go:47 +0xa5
github.com/l0nax/go-spew/spew.(*dumper).Write(0xc0004122a0, {0xc00040215d, 0x21, 0x21})
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/hex.go:150 +0x185
github.com/l0nax/go-spew/spew.HexDump({0xc00040215d, 0x21, 0x21}, 0x1)
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/hex.go:27 +0x114
github.com/l0nax/go-spew/spew.(*dumpState).dumpSlice(0xc00031deb8, {0x7aa360?, 0xc0004220d0?, 0x7aa360?})
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/dump.go:244 +0x556
github.com/l0nax/go-spew/spew.(*dumpState).dump(0xc00031deb8, {0x7aa360?, 0xc0004220d0?, 0x17?})
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/dump.go:384 +0xafb
github.com/l0nax/go-spew/spew.(*dumpState).dump(0xc00031deb8, {0x8392e0?, 0xc0004220c0?, 0x0?})
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/dump.go:453 +0x1025
github.com/l0nax/go-spew/spew.(*dumpState).dumpPtr(0xc00031deb8, {0x82e840?, 0xc0004220c0?, 0xc000583548?})
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/dump.go:161 +0x605
github.com/l0nax/go-spew/spew.(*dumpState).dump(0xc000304eb8, {0x82e840?, 0xc0004220c0?, 0xc000580c40?})
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/dump.go:277 +0xe8a
github.com/l0nax/go-spew/spew.fdump(0xb5c3a0, {0x8efac0, 0xc000186050}, {0xc000583790, 0x1, 0x1?})
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/dump.go:506 +0x1c6
github.com/l0nax/go-spew/spew.Dump(...)
	/home/kayos/go/pkg/mod/github.com/l0nax/go-spew@v1.3.0/spew/dump.go:549
git.tcp.direct/kayos/prox5.(*testSSHServer).handleConnection.func2()
	/home/kayos/Workshop/prox5/ssh_test.go:127 +0x134
created by git.tcp.direct/kayos/prox5.(*testSSHServer).handleConnection in goroutine 11
	/home/kayos/Workshop/prox5/ssh_test.go:119 +0x232
FAIL	git.tcp.direct/kayos/prox5	0.177s
FAIL
```

### Where

```golang
func HexEncode(dst, src []byte, colorize bool) ([]byte, int) {
	if colorize {
		return hexColorEncode(src)
	}

	j := 0

	for _, v := range src {
		dst[j] = hextable[v>>4]
		dst[j+1] = hextable[v&0x0f] // 0x0f => 0000 1111 // <--- dst's cap is only 1

		j += 2
	}

	return dst, len(src) * 2
}
```

---

I haven't yet dug deep enough to see the underlying cause, but it may make sense to implement `io.ReadWriter` during these ops ~(much like the stdlib `encoding/hex` package)~ instead of pushing directly into a destination byte slice. ~A simple bounds check for `dst` may hack this into not panicking, but~ clearly the problem is deeper than that.

Furthermore, in `HexEncode`; we are trying to press bytes directly into `dst` without calling append despite returning dst to the caller anyway. 

`[]byte` slices in golang [are referential](https://go.dev/play/p/WuGeF-Aa5pQ), so there is no need to return the modified slice. If we are going to return it, we might as well resize/reslice it as needed via append. This does incur minor allocation overhead but that's probably okay as spew is a debugging tool and shouldn't have a presence in production.

### Edits:
  - Looking further into this we see that `Encode` from `encoding/hex` does not return the destination slice. Additionally I now see that `hex.go` here is essentially a fork of the stdlib version. I also see that you do actually use append in `hexColorEncode`. I'm essentially left with more questions than answers, still looking into it :sweat_smile:

**Comment by yunginnanet** [comment]
For what it's worth, https://github.com/yunginnanet/go-spew/commit/39ed9057375381572d5c7a82d4ea87a465a1a897 has at least prevented the panic, though this is surely only a hacky workaround rather than a proper fix.

**Comment by yunginnanet** [comment]
I can't dump too much more time into this at this very moment, but I'll leave my current thoughts before closing this browser tab.

I'd say that it would make sense to programmatically determine the amount that a slice would grow in the event of colorization, we could grow the `dst` slice *before*  we send it off to `HexEncode` for potential colorization. This would allow us to maintain the original behavior of modifying `dst` directly without re-slicing by just always providing a byte slice of adequate capacity.

However there is a distinct possibility that I am missing a few things here :^)
